<?php
/**
 * The FullPeace Media To Post Public defines all functionality for the public-facing
 * sides of the plugin
 *
 * @package FPMTP
 *
 * The FullPeace Media To Post Public defines all functionality for the public-facing
 * sides of the plugin.
 *
 * This class defines the shortcodes used to display the custom posts
 * generated by the plugin.
 *
 * @since    0.1.0
 */
class FullPeace_Media_To_Post_Public {

    /**
     * Shortcode handler for [talks] shortcode
     * @param $atts
     */
    public function wmtp_custom_talks_shortcode( $atts ) {

        // Attributes
        extract( shortcode_atts(
                array(
                    'speaker' => '',
                    'series' => '',
                    'category' => '',
                ), $atts )
        );

        // Code
        // return WP_Query( array( 'post_type' => 'talk' ) );
    }

    /**
     * Register shortcodes
     */
    public function register_shortcodes()
    {
        add_shortcode( 'talks', array($this, 'wmtp_custom_talks_shortcode') );
    }
}