<?php
/**
 * The FullPeace Media To Post Public defines all functionality for the public-facing
 * sides of the plugin
 *
 * @package FPMTP
 *
 * The FullPeace Media To Post Public defines all functionality for the public-facing
 * sides of the plugin.
 *
 * This class defines the shortcodes used to display the custom posts
 * generated by the plugin.
 *
 * @since    0.1.0
 */
class FullPeace_Media_To_Post_Public {

    /**
     * A reference to the version of the plugin that is passed to this class from the caller.
     *
     * @access private
     * @var    string    $version    The current version of the plugin.
     */
    private $version;

    /**
     * Initializes this class and stores the current version of this plugin.
     *
     * @param    string    $version    The current version of this plugin.
     */
    public function __construct( $version ) {
        $this->version = $version;
    }
} 